WiiQare/frontend

- components/atoms/Breadcrumbs/index.test.js
- components/atoms/Button/NoAction.js
- components/atoms/Button/NoAction.test.js
- components/atoms/Card/Header/simple.js
- components/atoms/Card/Header/simple.test.js
- components/atoms/Card/Progress/index.js
- components/atoms/Card/Progress/index.test.js
- components/atoms/Icons/Badge.js
- components/atoms/Icons/Badge.test.js
- components/atoms/Loader/LoadingButton.js
- components/atoms/Loader/LoadingButton.test.js
- components/atoms/LogoHeader/index.test.jsx
- components/atoms/Toast/index.js
- components/atoms/Toast/index.test.js
- components/molecules/Sidebar/Bottom.js
- components/molecules/Sidebar/Bottom.test.js
- components/molecules/Sidebar/Index.js
- components/molecules/Sidebar/Index.test.js
- components/molecules/Sidebar/ItemBottom.js
- components/molecules/Sidebar/ItemBottom.test.js
- components/molecules/Sidebar/ItemSidebar.js
> test: few simple atoms and molecules

- components/atoms/Card/Header/index.js
- components/atoms/Card/Header/index.test.js
- components/atoms/Card/Notifications/Badge.test.js
- components/atoms/Card/Provider/index.js
- components/atoms/Card/Provider/index.test.js
- components/atoms/Input/RangeSlider.js
- components/atoms/Input/RangeSlider.test.js
- components/atoms/MenuHolder/index.jsx
- components/atoms/MenuHolder/index.test.jsx
> test: few more atoms

- components/atoms/Tab/__snapshots__/ItemHistory.test.js.snap
- jest.config.js
> test: mock splidejs-css

- components/atoms/Card/Notifications/Badge.test.js
- components/atoms/Card/Provider/index.js
- components/atoms/Loader/LoadingButton.js
- components/atoms/Modal/content.test.js
- components/atoms/Stepper/Forms/identity2.js
- components/atoms/Stepper/Forms/send.js
- components/atoms/Tab/ItemHistory.js
- components/atoms/Tab/PanelContent.test.js
- components/atoms/Tab/__snapshots__/PanelContent.test.js.snap
- components/molecules/Navbar/index.js
- components/molecules/Sidebar/Bottom.js
- components/organisms/Dashboard/Carousel.js
- components/organisms/Dashboard/ProviderFilter.js
- components/organisms/Transaction/details.js
- components/organisms/Transaction/quickly.js
- components/organisms/Wallet/index.js
- package.json
- pages/voucher/pass/[pass].js
- yarn.lock
> test: update and cleanup

- components/atoms/Button/Buy.test.js
- components/atoms/Button/Download.test.js
- components/atoms/Input/Country.test.js
> test: increase buttons' coverage

- components/organisms/Auth/StepRegistration.js
- components/organisms/Auth/StepRegistration.test.js
- components/organisms/Auth/__snapshots__/StepRegistration.test.js.snap
> test: registration step

- components/organisms/Auth/ResetForm.test.js
- components/organisms/Auth/__snapshots__/ResetForm.test.js.snap
- jest.config.js
- setupTests.js
> test: auth - reset form

- components/organisms/Auth/ForgotForm.test.js
- components/organisms/Auth/__snapshots__/ForgotForm.test.js.snap
> test: auth - forgot form

- components/organisms/Auth/LoginForm.test.js
- components/organisms/Auth/__snapshots__/LoginForm.test.js.snap
> test: auth - login form

- components/organisms/Dashboard/Carousel.test.js
- components/organisms/Dashboard/__snapshots__/Carousel.test.js.snap
- package.json
- styles/Carousel.module.css
- yarn.lock
> test: carousel

- components/organisms/Dashboard/ProviderFilter.test.js
- components/organisms/Dashboard/Voucher.test.js
- components/organisms/Dashboard/__snapshots__/ProviderFilter.test.js.snap
- components/organisms/Dashboard/__snapshots__/Voucher.test.js.snap
> test: voucher and provider filter

- components/organisms/Auth/Forms/__snapshots__/email.test.js.snap
- components/organisms/Auth/Forms/__snapshots__/information.test.js.snap
- components/organisms/Auth/Forms/__snapshots__/otp.test.js.snap
- components/organisms/Auth/Forms/email.js
- components/organisms/Auth/Forms/email.test.js
- components/organisms/Auth/Forms/information.test.js
- components/organisms/Auth/Forms/informations.js
- components/organisms/Auth/Forms/otp.js
- components/organisms/Auth/Forms/otp.test.js
> test: auth forms

- components/organisms/Auth/Forms/email.test.js
- package.json
- yarn.lock
> test: sending email using form

- components/organisms/Auth/Forms/information.test.js
> test: fill up sign up information form

- components/atoms/Stepper/Forms/identity.test.js
- components/atoms/Stepper/Forms/identity2.js
> test: add beneficiary

- components/atoms/Stepper/Forms/identity.test.js
> test: fill identity form

- .env
- components/atoms/MenuHolder/index.jsx
- components/molecules/Navbar/Drawer.js
- components/molecules/OnboardingScreen/index.jsx
- components/organisms/Transaction/quickly.js
- i18n.js
- utils/constants.js
> Fix some issues

- .env
- components/atoms/MenuHolder/index.jsx
- components/atoms/Stepper/Forms/send.js
- components/molecules/Navbar/Drawer.js
- components/molecules/OnboardingScreen/index.jsx
- components/organisms/Transaction/quickly.js
- i18n.js
- utils/constants.js
> Fix issue for link API for click generate voucher button

- .env
- components/atoms/MenuHolder/index.jsx
- components/atoms/Stepper/Forms/__snapshots__/kyc.test.js.snap
- components/atoms/Stepper/Forms/identity2.js
- components/atoms/Stepper/Forms/kyc.js
- components/atoms/Stepper/Forms/kyc.test.js
- components/atoms/Stepper/Forms/send.js
- components/atoms/Tab/ItemHistory.js
- components/molecules/Navbar/Drawer.js
- components/molecules/Navbar/Drawer/List.js
- components/molecules/Navbar/Drawer/__snapshots__/List.test.js.snap
- components/molecules/Navbar/Drawer/__snapshots__/index.test.js.snap
- components/molecules/Navbar/__snapshots__/Drawer.test.js.snap
- components/molecules/OnboardingScreen/index.jsx
- components/organisms/Auth/Forms/__snapshots__/otp.test.js.snap
- components/organisms/Auth/__snapshots__/ForgotForm.test.js.snap
- components/organisms/Auth/__snapshots__/LoginForm.test.js.snap
- components/organisms/Auth/__snapshots__/ResetForm.test.js.snap
- components/organisms/Transaction/quickly.js
- i18n.js
- lib/helper.js
- next.config.js
- pages/voucher/pass/[pass].js
- tests/pages/__snapshots__/login.test.js.snap
- tests/pages/__snapshots__/register.test.js.snap
- tests/pages/forgot/__snapshots__/password.test.js.snap
- tests/pages/reset-password/__snapshots__/[token].test.js.snap
- tests/pages/transactions/__snapshots__/index.test.js.snap
- utils/constants.js
- updated snapshot tests 
- Module to save KYC
- Module to check if account already filled KYC form authologic
> Fix some issues and module check KYC

- components/atoms/Stepper/Forms/identity2.js
- lib/helper.js
- pages/voucher/buy.js
**Fix editing player if going back from second screen + fix errors ( edit the player instead of adding it again )**
> fix editing patient

- components/atoms/Stepper/Forms/send.js
- components/atoms/Toast/index.js
- layouts/Dashboard.js
**Fixed popup notification using react portal, in order to see the message on mobile**
**Show message when SMS is succesfully sent**
> add popup notification for toast using react portal

- components/atoms/Stepper/Forms/identity2.js
**Fix for identity2 component, overwritten by Fcdpeter, replaying the changes for beneficiary editing**
> replay identity changes for edit beneficiary

- redux/reducer.test.js
- tests/pages/index.test.js
- tests/pages/invoices.test.js
- utils/constants.test.js
> more test coverage

- tests/pages/hospitals/index.test.js
- tests/pages/profile/index.test.js
- tests/pages/saving/[slug].test.js
- tests/pages/saving/__snapshots__/done.test.js.snap
- tests/pages/saving/done.test.js
- tests/pages/saving/index.test.js
- tests/pages/saving/new.test.js
- tests/pages/saving/operation/[saving].test.js
- tests/pages/saving/summary.test.js
- tests/pages/transactions/[id].test.js
> test for pages
